sonar.projectKey=Fraschesca03_skillhub-back
sonar.organization=fraschesca03
sonar.projectName=skillhub_back
sonar.projectVersion=1.0

# Sources à analyser
sonar.sources=app,routes,config,database
sonar.tests=tests

# Exclusions
sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**,bootstrap/cache/**

# Encodage
sonar.sourceEncoding=UTF-8

# PHP version
sonar.php.version=8.1

# Couverture de code (si tu utilises PHPUnit)
sonar.php.coverage.reportPaths=coverage.xml